### ISSUE TITLE
I like the swiwi design!

### ISSUE THREAD

**Issue by sylvaincentrale** [tatygrassini/tatygrassini.github.com#1]
Hey @tatygrassini!!

I like how you organize and animate all the pictures to a square format in the home page of SWIWI!!!
Where can I get it in HTML if it is available ? 

Thank you a lot!

Best,

Sylvain

**Comment by tatygrassini** [comment]
Sorry Sylvain, that's a client project and that design is copyrighted. But certainly it's a great inspiration for a future HTML template. Right now, I'm planning on building a couple for sale, so I'll keep you posted on that if you're interested.

Best for you as well,

Taty

**Comment by sylvaincentrale** [comment]
I understand, thank you for your reply.
It is a great idea!

We keep in touch.
Best,

Sylvain
